version: '3'
services:
  web:
    build: ./app
    restart: always
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
    env_file:
      - config/.secrets
    command: gunicorn wsgi:app -w 5 -b :8000 --timeout 3000 --reload
  redis:
    image: bitnami/redis:latest
    restart: always
    env_file:
      - config/.secrets
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  redis_data:
