version: '3'
services:
  web:
    build: ./app
    restart: always
    volumes:
      - ./app:/app
    expose:
      - '8000'
    depends_on:
      - redis
    env_file:
      - config/.secrets
    command: gunicorn app:app -w 5 -b :8000 --timeout 3000 --reload
  redis:
    image: redis:latest
    restart: always
    expose:
      - '6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
